### ISSUE TITLE
may be not working? and no XDA support link?

### ISSUE THREAD

**Issue by ZauronDark** [Magisk-Modules-Repo/hidden_settings#1]
note: my device running Lineage OS 16, 

I  used "su hidden" command on terminal, as instructed, but nothing is happening. (ofcource, I did reboot after installation, and root permission granted)

also, I see there is no link to XDA forums, as this Github is not exactly a support site, hope you consider.

**Comment by skittles9823** [comment]
`su -c hidden` or `su` enter `hidden`
